In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from covid19dh import covid19
from scipy.integrate import odeint

In [6]:
##Import the data

x_ind, src_ind = covid19("IND")
x_chn, src_chn = covid19("CHN")
x_jpn, src_jpn = covid19("JPN")
x_swe, src_ind = covid19("SWE")
x_ita, src_ita = covid19("ITA")
x_fra, src_fra = covid19("FRA")

We have invested a lot of time and effort in creating COVID-19 Data Hub, please cite the following when using it:

	Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

A BibTeX entry for LaTeX users is

	@Article{,
		title = {COVID-19 Data Hub},
		year = {2020},
		doi = {10.21105/joss.02376},
		author = {Emanuele Guidotti and David Ardia},
		journal = {Journal of Open Source Software},
		volume = {5},
		number = {51},
		pages = {2376},
	}

To hide this message use 'verbose = False'.
We have invested a lot of time and effort in creating COVID-19 Data Hub, please cite the following when using it:

	Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

A BibTeX entry for LaTeX users is

	@Article{,
		title = {COVID-19 Data Hub},
		year = {2020},
		doi = {10.21105/joss.02376},
		author = {Emanuele Guidotti and David Ardia},
		journal = {Journal of Open Source Software},
		volume = {5},
		number = {51},
		pages = {2376},
	}

To hide this message use 'verbose = False'.
We have invested a lot of time and effort in creating COVID-19 Data Hub, please cite the following when using it:

	Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

A BibTeX entry for LaTeX users is

	@Article{,
		title = {COVID-19 Data Hub},
		year = {2020},
		doi = {10.21105/joss.02376},
		author = {Emanuele Guidotti and David Ardia},
		journal = {Journal of Open Source Software},
		volume = {5},
		number = {51},
		pages = {2376},
	}

To hide this message use 'verbose = False'.
We have invested a lot of time and effort in creating COVID-19 Data Hub, please cite the following when using it:

	Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

A BibTeX entry for LaTeX users is

	@Article{,
		title = {COVID-19 Data Hub},
		year = {2020},
		doi = {10.21105/joss.02376},
		author = {Emanuele Guidotti and David Ardia},
		journal = {Journal of Open Source Software},
		volume = {5},
		number = {51},
		pages = {2376},
	}

To hide this message use 'verbose = False'.
We have invested a lot of time and effort in creating COVID-19 Data Hub, please cite the following when using it:

	Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

A BibTeX entry for LaTeX users is

	@Article{,
		title = {COVID-19 Data Hub},
		year = {2020},
		doi = {10.21105/joss.02376},
		author = {Emanuele Guidotti and David Ardia},
		journal = {Journal of Open Source Software},
		volume = {5},
		number = {51},
		pages = {2376},
	}

To hide this message use 'verbose = False'.
We have invested a lot of time and effort in creating COVID-19 Data Hub, please cite the following when using it:

	Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

A BibTeX entry for LaTeX users is

	@Article{,
		title = {COVID-19 Data Hub},
		year = {2020},
		doi = {10.21105/joss.02376},
		author = {Emanuele Guidotti and David Ardia},
		journal = {Journal of Open Source Software},
		volume = {5},
		number = {51},
		pages = {2376},
	}

To hide this message use 'verbose = False'.

In [7]:
x_ita

,id,date,tests,confirmed,recovered,deaths,hosp,vent,icu,population,...,currency,administrative_area_level,administrative_area_level_1,administrative_area_level_2,administrative_area_level_3,latitude,longitude,key,key_apple_mobility,key_google_mobility
25660,ITA,2020-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25661,ITA,2020-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25662,ITA,2020-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25663,ITA,2020-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25664,ITA,2020-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,ITA,2020-10-31,15784461.0,679430.0,289426.0,38618.0,19809.0,NaN,1843.0,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25944,ITA,2020-11-01,15967918.0,709335.0,292380.0,38826.0,20841.0,NaN,1939.0,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25945,ITA,2020-11-02,16103649.0,731588.0,296017.0,39059.0,21862.0,NaN,2022.0,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25946,ITA,2020-11-03,16285936.0,759829.0,302275.0,39412.0,23339.0,NaN,2225.0,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT
25947,ITA,2020-11-04,16497767.0,790377.0,307378.0,39764.0,24408.0,NaN,2292.0,60421760,...,EUR,1,Italy,NaN,NaN,43.0,12.0,NaN,Italy,IT

In [ ]:
population=60421760

Y = x_ind.iloc[61:,4].values #Stores Daily Confirmed